import type { Incident } from '../types'

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: 'INC-001',
    nercId: 'NERC-2024-0710-CAI',
    date: new Date('2024-07-10T02:34:00').getTime(),
    type: 'frequency',
    region: 'CAISO',
    severity: 'critical',
    duration: 1420,
    loadImpact: 3200,
    status: 'resolved',
    narrative: 'Sudden frequency excursion to 59.84 Hz detected following unexpected trip of Diablo Canyon Unit 2. MONITOR agent identified deviation within 12 seconds. DIAGNOSE retrieved 4 similar IBR-related incidents. Shunt capacitor banks removed per WATT recommendation. Frequency recovered to nominal in 23 minutes.',
    actionsTaken: [
      { timestamp: new Date('2024-07-10T02:34:12').getTime(), action: 'WATT MONITOR detected frequency deviation: 59.84 Hz', operator: 'WATT' },
      { timestamp: new Date('2024-07-10T02:35:01').getTime(), action: 'Operator Maria acknowledged alarm, initiated DIAGNOSE', operator: 'Maria K.' },
      { timestamp: new Date('2024-07-10T02:36:45').getTime(), action: 'Approved WATT recommendation: Remove 3 shunt capacitor banks', operator: 'Maria K.' },
      { timestamp: new Date('2024-07-10T02:48:00').getTime(), action: 'Frequency restored to 60.01 Hz — event resolved', operator: 'System' },
    ],
    outcome: 'Frequency restored to nominal within 23 minutes. No customer outages. 3,200 MW load impact managed through demand response. WATT recommendation accuracy: 94%.',
    similarityScore: 0.94,
  },
  {
    id: 'INC-002',
    nercId: 'NERC-2021-0910-ERC',
    date: new Date('2021-09-10T14:22:00').getTime(),
    type: 'frequency',
    region: 'ERCOT',
    severity: 'critical',
    duration: 4680,
    loadImpact: 8900,
    status: 'resolved',
    narrative: 'Cascading frequency excursion in ERCOT following IBR (Inverter-Based Resource) fault. Multiple solar and wind units tripped simultaneously due to grid disturbance. Frequency dropped to 59.71 Hz — approaching UFLS threshold. Emergency protocols engaged.',
    actionsTaken: [
      { timestamp: new Date('2021-09-10T14:22:05').getTime(), action: 'Frequency alarm: 59.71 Hz — UFLS threshold proximity' },
      { timestamp: new Date('2021-09-10T14:23:00').getTime(), action: 'Emergency reserve dispatch initiated' },
      { timestamp: new Date('2021-09-10T14:45:00').getTime(), action: 'IBR units resynced, frequency stabilizing' },
      { timestamp: new Date('2021-09-10T15:42:00').getTime(), action: 'Full recovery achieved — 59.99 Hz' },
    ],
    outcome: 'ERCOT nearly triggered Under-Frequency Load Shedding. 8,900 MW at risk. Recovery time 78 minutes. Led to NERC reliability standard revision for IBR behavior during grid disturbances.',
    similarityScore: 0.88,
  },
  {
    id: 'INC-003',
    nercId: 'NERC-2021-0214-ERC',
    date: new Date('2021-02-14T06:15:00').getTime(),
    type: 'weather',
    region: 'ERCOT',
    severity: 'critical',
    duration: 259200,
    loadImpact: 34000,
    status: 'resolved',
    narrative: 'Historic Winter Storm Uri caused catastrophic generation failures across ERCOT. Extreme cold weather disabled natural gas plants, wind turbines, and solar arrays. Rolling blackouts affected 4.5 million customers. Grid frequency dropped perilously close to automatic shutdown threshold.',
    actionsTaken: [
      { timestamp: new Date('2021-02-14T06:15:00').getTime(), action: 'Emergency load shedding initiated — 34,000 MW deficit' },
      { timestamp: new Date('2021-02-14T12:00:00').getTime(), action: 'Controlled rolling blackouts activated' },
      { timestamp: new Date('2021-02-17T00:00:00').getTime(), action: 'Generation recovery begun as temperatures rose' },
      { timestamp: new Date('2021-02-20T00:00:00').getTime(), action: 'Grid restored to normal operations' },
    ],
    outcome: 'Largest grid emergency in US history. 4.5M customers lost power for up to 4 days. 246 deaths attributed to storm. Led to weatherization mandates and infrastructure reforms.',
  },
  {
    id: 'INC-004',
    nercId: 'NERC-2022-0622-CAI',
    date: new Date('2022-06-22T15:45:00').getTime(),
    type: 'overload',
    region: 'CAISO',
    severity: 'major',
    duration: 7200,
    loadImpact: 5200,
    status: 'resolved',
    narrative: 'Heat wave emergency across California. Record demand reached 52,061 MW — nearly exceeding all-time records. CAISO issued Flex Alert requesting voluntary conservation. Smart inverter coordination prevented worst-case scenario.',
    actionsTaken: [
      { timestamp: new Date('2022-06-22T15:45:00').getTime(), action: 'Flex Alert issued — voluntary conservation request' },
      { timestamp: new Date('2022-06-22T16:30:00').getTime(), action: 'Demand response programs activated — 1,200 MW curtailed' },
      { timestamp: new Date('2022-06-22T18:00:00').getTime(), action: 'Import from neighboring BAs increased by 2,800 MW' },
      { timestamp: new Date('2022-06-22T21:30:00').getTime(), action: 'Load below critical threshold — emergency resolved' },
    ],
    outcome: 'No customer outages achieved through demand response and imports. 5,200 MW effectively managed. Conservation efforts reduced peak by 2.4%.',
  },
  {
    id: 'INC-005',
    nercId: 'NERC-2023-0815-MIS',
    date: new Date('2023-08-15T11:20:00').getTime(),
    type: 'voltage',
    region: 'MISO',
    severity: 'major',
    duration: 3600,
    loadImpact: 1800,
    status: 'resolved',
    narrative: 'Voltage instability event in MISO eastern region following 500kV transmission line fault. Reactive power deficit caused voltage depression in Michigan-Indiana corridor. Capacitor switching and generator reactive boost corrected.',
    actionsTaken: [
      { timestamp: new Date('2023-08-15T11:20:00').getTime(), action: 'Voltage alarm: 0.94 pu on 500kV bus — WECC threshold' },
      { timestamp: new Date('2023-08-15T11:25:00').getTime(), action: 'Capacitor banks switched in — reactive injection 300 MVAR' },
      { timestamp: new Date('2023-08-15T11:35:00').getTime(), action: 'Generator reactive boost authorized — 4 units' },
      { timestamp: new Date('2023-08-15T12:20:00').getTime(), action: 'Voltage restored to 0.98 pu — normal operation' },
    ],
    outcome: 'Voltage restored in 60 minutes. 1,800 MW protected from potential outage. Transmission line repaired within 4 hours.',
  },
  {
    id: 'INC-006',
    nercId: 'NERC-2023-1103-PJM',
    date: new Date('2023-11-03T03:10:00').getTime(),
    type: 'renewable',
    region: 'PJM',
    severity: 'minor',
    duration: 1800,
    loadImpact: 2100,
    status: 'resolved',
    narrative: 'Rapid wind ramp-down event in PJM western region. Wind generation dropped 4,200 MW in 15 minutes as cold front passed. AGC response was nominal but frequency dipped to 59.96 Hz during transition.',
    actionsTaken: [
      { timestamp: new Date('2023-11-03T03:10:00').getTime(), action: 'Wind ramp detected — WATT issued advisory' },
      { timestamp: new Date('2023-11-03T03:15:00').getTime(), action: 'Fast-start gas units dispatched — 1,200 MW in 5 minutes' },
      { timestamp: new Date('2023-11-03T03:28:00').getTime(), action: 'Frequency stabilized at 59.98 Hz' },
    ],
    outcome: 'Frequency maintained above 59.95 Hz threshold. Demand response supplemented by fast-start gas. No customer impact.',
  },
  {
    id: 'INC-007',
    nercId: 'NERC-2024-0321-SPP',
    date: new Date('2024-03-21T19:55:00').getTime(),
    type: 'datacenter',
    region: 'SPP',
    severity: 'minor',
    duration: 900,
    loadImpact: 580,
    status: 'resolved',
    narrative: 'Hyperscale data center campus in Kansas triggered UPS transfer event, causing sudden 580 MW load step. Grid frequency momentarily dipped to 59.97 Hz. Faster-than-expected recovery attributed to AGC response and co-located battery storage.',
    actionsTaken: [
      { timestamp: new Date('2024-03-21T19:55:00').getTime(), action: 'Load step detected: 580 MW in <1 second' },
      { timestamp: new Date('2024-03-21T19:55:30').getTime(), action: 'Battery storage co-located at campus responded automatically' },
      { timestamp: new Date('2024-03-21T20:10:00').getTime(), action: 'Normal operation confirmed' },
    ],
    outcome: 'Event resolved in 15 minutes. No operator intervention required. Battery storage absorbed load step effectively.',
  },
  {
    id: 'INC-008',
    nercId: 'NERC-2022-1210-NYI',
    date: new Date('2022-12-10T07:30:00').getTime(),
    type: 'cyber',
    region: 'NYISO',
    severity: 'major',
    duration: 14400,
    loadImpact: 0,
    status: 'resolved',
    narrative: 'Cybersecurity intrusion attempt detected on NYISO SCADA system. All market operations suspended as precaution. Physical override protocols activated. No grid operations were affected. FBI and CISA notified.',
    actionsTaken: [
      { timestamp: new Date('2022-12-10T07:30:00').getTime(), action: 'Anomalous SCADA login attempts detected from 47 source IPs' },
      { timestamp: new Date('2022-12-10T07:35:00').getTime(), action: 'Market operations suspended — physical override activated' },
      { timestamp: new Date('2022-12-10T09:00:00').getTime(), action: 'FBI and CISA notified — forensic investigation begun' },
      { timestamp: new Date('2022-12-10T11:30:00').getTime(), action: 'Clean system verified — operations restored' },
    ],
    outcome: 'No grid impact. Intrusion contained at perimeter. System restored in 4 hours. Attack attributed to nation-state actor. Resulted in enhanced OT network segmentation.',
  },
  {
    id: 'INC-009',
    nercId: 'NERC-2024-0508-WEC',
    date: new Date('2024-05-08T16:20:00').getTime(),
    type: 'renewable',
    region: 'WECC',
    severity: 'info',
    duration: 3600,
    loadImpact: 3800,
    status: 'resolved',
    narrative: 'Solar over-generation event during spring low-load period in WECC. Duck curve deepened beyond forecast. CAISO requested curtailment of 3,800 MW of solar to prevent frequency overshoot. Battery storage absorbed excess during curtailment.',
    actionsTaken: [
      { timestamp: new Date('2024-05-08T16:20:00').getTime(), action: 'Solar over-generation alert: +3,800 MW above forecast' },
      { timestamp: new Date('2024-05-08T16:25:00').getTime(), action: 'Curtailment orders issued to 142 solar facilities' },
      { timestamp: new Date('2024-05-08T16:45:00').getTime(), action: 'Battery charging initiated to absorb excess — 1,200 MWh stored' },
      { timestamp: new Date('2024-05-08T17:20:00').getTime(), action: 'Generation balanced — curtailment orders lifted' },
    ],
    outcome: 'Frequency maintained within ±0.02 Hz. 3,800 MW curtailed (estimated $4.2M cost). Battery storage effectiveness confirmed for duck curve management.',
  },
  {
    id: 'INC-010',
    nercId: 'NERC-2023-0630-PJM',
    date: new Date('2023-06-30T14:00:00').getTime(),
    type: 'cascading',
    region: 'PJM',
    severity: 'major',
    duration: 5400,
    loadImpact: 11200,
    status: 'resolved',
    narrative: 'N-2 contingency event in PJM following near-simultaneous outage of two 765kV transmission lines due to equipment failure during high-load conditions. Power flow redistribution caused thermal overloads on adjacent lines, triggering protective relaying cascade.',
    actionsTaken: [
      { timestamp: new Date('2023-06-30T14:00:00').getTime(), action: 'Line 765kV-PJM-A tripped — N-1 contingency declared' },
      { timestamp: new Date('2023-06-30T14:01:30').getTime(), action: 'Line 765kV-PJM-B tripped — N-2 contingency — emergency procedures' },
      { timestamp: new Date('2023-06-30T14:05:00').getTime(), action: 'Thermal overload cascade arrested — 3 lines redispatched' },
      { timestamp: new Date('2023-06-30T15:30:00').getTime(), action: 'Full N-1 compliance restored' },
    ],
    outcome: 'Cascade arrested before customer outages. 11,200 MW at risk managed through rapid redispatch. Recovery in 90 minutes. Resulted in transmission maintenance schedule review.',
  },
]
