import type { Playbook } from '../types'

export const MOCK_PLAYBOOKS: Playbook[] = [
  {
    id: 'PB-001',
    title: 'Frequency Excursion > 0.05 Hz',
    category: 'frequency',
    description: 'Response procedure for sustained frequency deviations exceeding NERC BAL-003 thresholds',
    wattConfidence: 0.91,
    lastUsed: Date.now() - 3 * 24 * 60 * 60 * 1000,
    tags: ['frequency', 'NERC', 'BAL-003', 'emergency'],
    steps: [
      { id: 's1', order: 1, title: 'Confirm deviation', description: 'Verify frequency reading on backup PMU. Confirm deviation is not instrument error. Document timestamp and magnitude.', duration: 60 },
      { id: 's2', order: 2, title: 'Identify source', description: 'Check recent generation trips in real-time monitoring. Review interconnection data for sudden imbalances. Identify the balancing area of origin.', duration: 120, criticalWarning: 'Do not delay this step — frequency may continue degrading during investigation' },
      { id: 's3', order: 3, title: 'Dispatch emergency reserves', description: 'Contact regulation reserve providers. Dispatch fast-response units. Target: 100% of ACE recovery within 10 minutes per NERC BAL-001.', duration: 300 },
      { id: 's4', order: 4, title: 'Coordinate with neighboring BAs', description: 'Notify adjacent balancing areas. Request emergency assistance if deviation exceeds ±0.1 Hz. Activate E-TAG emergency transactions.', duration: 180 },
      { id: 's5', order: 5, title: 'Monitor recovery', description: 'Confirm frequency trending back toward nominal. Log all actions with timestamps. Update ops log with WATT recommendation outcomes.', duration: 600 },
      { id: 's6', order: 6, title: 'Document and notify', description: 'File NERC event report if frequency exceeded 59.95 or 60.05 Hz for >1 minute. Notify NERC reliability coordinator. Update shift log.', duration: 300, precedentRefs: ['NERC-2024-0710-CAI', 'NERC-2021-0910-ERC'] },
      { id: 's7', order: 7, title: 'Post-event analysis', description: 'Run WATT post-event analysis to identify root cause and similar historical events. Generate corrective action report.', duration: 1800 },
      { id: 's8', order: 8, title: 'Restore normal operations', description: 'Return units to scheduled dispatch. Clear emergency notifications. Update watchlist. Brief incoming shift if during handoff window.', duration: 600 },
    ],
  },
  {
    id: 'PB-002',
    title: 'Data Center UPS Transfer Response',
    category: 'datacenter',
    description: 'Procedure for managing sudden load steps from hyperscale data center UPS transfer events',
    wattConfidence: 0.87,
    lastUsed: Date.now() - 12 * 24 * 60 * 60 * 1000,
    tags: ['datacenter', 'load-step', 'UPS', 'frequency'],
    steps: [
      { id: 's1', order: 1, title: 'Detect and quantify load step', description: 'Confirm load step magnitude from telemetry. Identify the facility causing the event. Estimate duration based on UPS run-time specifications.', duration: 30 },
      { id: 's2', order: 2, title: 'Assess frequency impact', description: 'Monitor frequency deviation. Calculate expected nadir based on load step and inertia. Determine if automatic battery storage response is sufficient.', duration: 60 },
      { id: 's3', order: 3, title: 'Contact data center operator', description: 'Notify DC operations team of grid impact. Request estimated duration of UPS event. Coordinate return-to-grid timeline.', duration: 120 },
      { id: 's4', order: 4, title: 'Dispatch supplemental response', description: 'If frequency below 59.97 Hz, dispatch fast-start peaker units. Request demand response activation if needed.', duration: 300, criticalWarning: 'DC load can return simultaneously — prepare for reverse load step' },
      { id: 's5', order: 5, title: 'Monitor return event', description: 'Prepare for load return when DC reconnects to grid. Coordinate with fast-start units to absorb overshoot. Monitor for 5 minutes post-return.', duration: 600 },
      { id: 's6', order: 6, title: 'Log and update DC watch', description: 'Log event in shift timeline. Update DC load watch threshold if pattern indicates recurring behavior.', duration: 180 },
    ],
  },
  {
    id: 'PB-003',
    title: 'Cascading Outage N-2 Contingency',
    category: 'cascading',
    description: 'Emergency procedure for N-2 or worse contingency events with potential for cascade',
    wattConfidence: 0.82,
    lastUsed: Date.now() - 45 * 24 * 60 * 60 * 1000,
    tags: ['N-2', 'contingency', 'cascade', 'emergency', 'NERC'],
    steps: [
      { id: 's1', order: 1, title: 'Declare N-2 emergency', description: 'Confirm second contingency has occurred. Initiate emergency operations protocol. All non-essential communications suspended.', duration: 60, criticalWarning: 'TIME CRITICAL — cascade can propagate in seconds' },
      { id: 's2', order: 2, title: 'Arrest thermal cascade', description: 'Identify overloaded lines. Issue emergency redispatch orders to reduce loading on affected segments. Target: below emergency ratings within 5 minutes.', duration: 300 },
      { id: 's3', order: 3, title: 'Coordinate with neighboring BAs', description: 'Declare emergency to all adjacent BAs. Request maximum emergency assistance. Activate all available import transactions.', duration: 120 },
      { id: 's4', order: 4, title: 'Stabilize frequency', description: 'Monitor frequency carefully during redispatch. Be prepared for further trips as protective relays respond. Maintain >59.90 Hz.', duration: 600 },
      { id: 's5', order: 5, title: 'Notify NERC RC', description: 'Contact NERC Reliability Coordinator immediately. Report event details, actions taken, current system state.', duration: 180 },
      { id: 's6', order: 6, title: 'Restore N-1 compliance', description: 'Work toward restoring N-1 contingency compliance. Bring backup generation online. Restore normal power flows.', duration: 3600 },
    ],
  },
  {
    id: 'PB-004',
    title: 'Renewable Rapid Ramp Response',
    category: 'renewable',
    description: 'Procedure for managing rapid wind or solar ramp events exceeding AGC capability',
    wattConfidence: 0.89,
    lastUsed: Date.now() - 7 * 24 * 60 * 60 * 1000,
    tags: ['wind', 'solar', 'ramp', 'AGC', 'forecast'],
    steps: [
      { id: 's1', order: 1, title: 'Identify ramp event', description: 'Confirm generation ramp magnitude and direction. Compare to forecast. Identify if ramp is within AGC capability.', duration: 60 },
      { id: 's2', order: 2, title: 'Pre-position fast-response units', description: 'Dispatch fast-start gas units to synchronized standby. Activate demand response programs on standby. Alert battery storage operators.', duration: 300 },
      { id: 's3', order: 3, title: 'Coordinate curtailment if needed', description: 'For over-generation: issue curtailment orders in merit order. For under-generation: dispatch reserves. Maintain 10% reserve margin.', duration: 600 },
      { id: 's4', order: 4, title: 'Monitor and adjust', description: 'Monitor frequency and ACE continuously. Adjust dispatch as ramp develops. Coordinate with meteorology for updated forecast.', duration: 1200 },
      { id: 's5', order: 5, title: 'Document and update forecast', description: 'Log event. Update renewable forecast confidence for next 4-hour period. Create WATT watch item for pattern recurrence.', duration: 300 },
    ],
  },
  {
    id: 'PB-005',
    title: 'Voltage Instability — Reactive Support',
    category: 'voltage',
    description: 'Response to voltage instability events requiring reactive power support',
    wattConfidence: 0.85,
    lastUsed: Date.now() - 22 * 24 * 60 * 60 * 1000,
    tags: ['voltage', 'reactive', 'capacitor', 'STATCOM'],
    steps: [
      { id: 's1', order: 1, title: 'Confirm voltage depression', description: 'Verify voltage reading on multiple buses. Confirm not instrument error. Calculate Q-V sensitivity for affected area.', duration: 90 },
      { id: 's2', order: 2, title: 'Switch in capacitor banks', description: 'Switch in available shunt capacitor banks in affected area. Prioritize 500kV bus support. Monitor voltage response.', duration: 120, criticalWarning: 'Switching in too many capacitors can cause over-voltage on recovery' },
      { id: 's3', order: 3, title: 'Request generator reactive boost', description: 'Contact generators in affected area. Request maximum reactive output within capability curve limits. Verify AVR setpoints.', duration: 180 },
      { id: 's4', order: 4, title: 'Assess load shedding risk', description: 'If voltage below 0.90 pu and not recovering, prepare for emergency load shedding. Calculate minimum load shed to stabilize voltage.', duration: 300 },
      { id: 's5', order: 5, title: 'Restore normal voltage profile', description: 'Monitor as voltage recovers. Remove excess reactive support to prevent over-voltage. Return to normal voltage schedule.', duration: 600 },
    ],
  },
]
